server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://crover:bdCo-v95.@cluster0.nawut.mongodb.net/db_deposit?retryWrites=true&w=majority
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
